from filters import *
from PIL import Image

image = Image.open("sky.jpg")
greyscale_filter(image)
image = Image.open("sky.jpg")
green_filter(image)
image = Image.open("sky.jpg")
greyscale_alternative_filter(image)
image = Image.open("sky.jpg")
blue_filter(image)
image = Image.open("sky.jpg")
dark_blue_filter(image)
image = Image.open("sky.jpg")
yellow_filter(image)
image = Image.open("sky.jpg")
reduce_opacity_filter(image, 3)
image = Image.open("sky.jpg")
blur_filter_3x3(image)
image = Image.open("sky.jpg")
blur_filter_4x3(image)
image = Image.open("sky.jpg")
blur_filter(image)
image = Image.open("sky.jpg")
luminosity_filter(image, 3)
image = Image.open("sky.jpg")
contrast_filter(image)
image = Image.open("sky.jpg")
crop_filter(image, (50, 50), (100, 100))
image = Image.open("sky.jpg")
blur_lib_filter(image, 30)
image = Image.open("sky.jpg")
sharpen_filter(image)
image = Image.open("sky.jpg")
unsharpen_mask_filter(image, 4)
image = Image.open("sky.jpg")
edge_detection_filter(image)
image = Image.open("sky.jpg")

